version: 0.2


phases:
  install:
    runtime-versions:
      nodejs: 14
  pre_build:
    commands:
      - export BUILD_BRANCH="`echo $CODEBUILD_WEBHOOK_HEAD_REF | cut -d \"/\" -f 3`"
      - echo "Build branch ${BUILD_BRANCH}"
      - git checkout ${BUILD_BRANCH}
      - export GITHUB_BRANCH=$(git describe --all)
      - echo "Github branch ${GITHUB_BRANCH}"
      - apt-get update &&
      - >-
        apt-get install -yqq libgtk2.0-0 libgconf-2-4 xvfb ca-certificates fonts-liberation libappindicator3-1 libasound2 libatk-bridge2.0-0 libatk1.0-0 
        libc6 libcairo2 libcups2 libdbus-1-3 libexpat1 libfontconfig1 libgbm1 libgcc1 libglib2.0-0 libgtk-3-0 libnspr4 libnss3 libpango-1.0-0 libpangocairo-1.0-0
        libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 lsb-release wget xdg-utils
      - npm install && npm install -g allure-commandline
  build:
    commands:
      - echo Build started on `date`
      - pwd
      - ls -lah
      - ./start_codeceptjs.sh
  post_build:
    commands:
      - echo Build completed on `date`
